In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [2]:
# Load the data into a Pandas DataFrame

df = pd.read_csv("Data/E0.csv")

In [3]:
print(type(df))

<class 'pandas.DataFrame'>

In [4]:
# Make a copy of the original dataset

df_original = df.copy()

In [5]:
# Check the size of the dataset

print(df.shape)

(380, 132)

In [6]:
# View the first few rows

df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [7]:
# Choosing the Number of Rows to Observe

df.head(20)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
5,E0,16/08/2025,17:30,Wolves,Man City,0,4,A,0,2,...,1.98,1.88,2.07,1.86,2.04,1.88,1.91,1.81,2.05,1.94
6,E0,17/08/2025,14:00,Chelsea,Crystal Palace,0,0,D,0,0,...,1.85,2.00,1.74,2.21,1.85,2.03,1.79,1.97,1.88,2.12
7,E0,17/08/2025,14:00,Nott'm Forest,Brentford,3,1,H,3,0,...,1.88,1.98,2.18,1.76,1.91,1.98,1.86,1.89,1.96,2.03
8,E0,17/08/2025,16:30,Man United,Arsenal,0,1,A,0,1,...,1.88,1.98,1.91,2.01,1.93,1.98,1.86,1.89,2.00,1.99
9,E0,18/08/2025,20:00,Leeds,Everton,1,0,H,0,0,...,2.05,1.80,2.02,1.90,2.05,1.86,1.91,1.78,2.14,1.86
10,E0,22/08/2025,20:00,West Ham,Chelsea,1,5,A,1,3,...,1.83,2.03,2.06,1.87,1.95,2.03,1.85,1.89,2.02,1.96
11,E0,23/08/2025,12:30,Man City,Tottenham,0,2,A,0,2,...,1.87,1.87,1.83,2.11,1.87,2.09,1.81,1.95,1.94,2.04
12,E0,23/08/2025,15:00,Bournemouth,Wolves,1,0,H,1,0,...,2.05,1.80,2.05,1.88,2.07,1.81,1.99,1.76,2.17,1.83
13,E0,23/08/2025,15:00,Brentford,Aston Villa,1,0,H,1,0,...,2.03,1.83,1.94,1.98,2.03,1.93,1.92,1.78,2.04,1.93
14,E0,23/08/2025,15:00,Burnley,Sunderland,2,0,H,0,0,...,2.00,1.85,2.00,1.93,2.02,1.85,1.94,1.80,2.09,1.90
15,E0,23/08/2025,17:30,Arsenal,Leeds,5,0,H,2,0,...,2.00,1.85,2.04,1.88,2.00,1.91,1.91,1.85,2.06,1.92
16,E0,24/08/2025,14:00,Crystal Palace,Nott'm Forest,1,1,D,1,0,...,1.99,1.74,2.10,1.84,2.04,1.81,1.95,1.77,2.13,1.88
17,E0,24/08/2025,14:00,Everton,Brighton,2,0,H,1,0,...,2.04,1.72,2.24,1.73,2.10,1.76,2.06,1.72,2.24,1.80
18,E0,24/08/2025,16:30,Fulham,Man United,1,1,D,0,0,...,2.03,1.83,2.04,1.88,2.04,1.83,2.01,1.71,2.13,1.87
19,E0,25/08/2025,20:00,Newcastle,Liverpool,2,3,A,0,1,...,1.83,2.03,1.87,2.07,1.85,2.03,1.83,1.88,1.93,2.06

In [8]:
# View all column names
df.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA',
       'AvgCAHH', 'AvgCAHA', 'BFECAHH', 'BFECAHA'],
      dtype='str', length=132)

In [9]:
# Check the data types of each column
df.dtypes

Div             str
Date            str
Time            str
HomeTeam        str
AwayTeam        str
             ...
MaxCAHA     float64
AvgCAHH     float64
AvgCAHA     float64
BFECAHH     float64
BFECAHA     float64
Length: 132, dtype: object

In [10]:
# Check for duplicate rows

duplicate_rows = df[df.duplicated()]
print("Number of duplicate row: ", len(duplicate_rows))
duplicate_rows#Check for duplicate row

Number of duplicate row:  0

Empty DataFrame
Columns: [Div, Date, Time, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR, B365H, B365D, B365A, BFDH, BFDD, BFDA, BMGMH, BMGMD, BMGMA, BVH, BVD, BVA, BWH, BWD, BWA, CLH, CLD, CLA, LBH, LBD, LBA, PSH, PSD, PSA, MaxH, MaxD, MaxA, AvgH, AvgD, AvgA, BFEH, BFED, BFEA, B365>2.5, B365<2.5, P>2.5, P<2.5, Max>2.5, Max<2.5, Avg>2.5, Avg<2.5, BFE>2.5, BFE<2.5, AHh, B365AHH, B365AHA, PAHH, PAHA, MaxAHH, MaxAHA, AvgAHH, AvgAHA, BFEAHH, BFEAHA, B365CH, B365CD, B365CA, BFDCH, BFDCD, BFDCA, BMGMCH, BMGMCD, BMGMCA, BVCH, BVCD, BVCA, BWCH, BWCD, BWCA, CLCH, CLCD, CLCA, LBCH, LBCD, LBCA, PSCH, ...]
Index: []

[0 rows x 132 columns]

In [11]:
# check for miissing values

missing_values = df.isnull().sum()

print(missing_values[missing_values > 0])

BFDH          1
BFDD          1
BFDA          1
BMGMH         2
BMGMD         2
BMGMA         2
BVH           2
BVD           2
BVA           2
CLH          98
CLD          98
CLA          98
LBH          94
LBD          94
LBA          94
PSH         170
PSD         170
PSA         170
BFEH         20
BFED         20
BFEA         20
P>2.5       170
P<2.5       170
BFE>2.5      20
BFE<2.5      20
AHh           1
PAHH        170
PAHA        170
BFEAHH       20
BFEAHA       20
BFDCH         8
BFDCD         8
BFDCA         8
BVCH          8
BVCD          8
BVCA          8
CLCH        120
CLCD        120
CLCA        120
LBCH         99
LBCD         99
LBCA         99
PSCH        170
PSCD        170
PSCA        170
BFECH        22
BFECD        22
BFECA        22
PC>2.5      170
PC<2.5      170
BFEC>2.5     22
BFEC<2.5     22
PCAHH       170
PCAHA       170
BFECAHH      22
BFECAHA      22
dtype: int64

In [12]:
# colums we plsn to use for the football project

football_columns = [
    "Div", "Date", "Time",
    "HomeTeam", "AwayTeam",
    "FTHG", "FTAG", "FTR",
    "HTHG", "HTAG", "HTR",
    "Referee",
    "HS", "AS",
    "HST", "AST",
    "HF", "AF",
    "HC", "AC",
    "HY", "AY",
    "HR", "AR"
]

# chek misssing values onaly in the colums we plan to use 

print(df[football_columns].isnull().sum())

Div         0
Date        0
Time        0
HomeTeam    0
AwayTeam    0
FTHG        0
FTAG        0
FTR         0
HTHG        0
HTAG        0
HTR         0
Referee     0
HS          0
AS          0
HST         0
AST         0
HF          0
AF          0
HC          0
AC          0
HY          0
AY          0
HR          0
AR          0
dtype: int64

In [13]:
# kepp only the colums in football_columns 

df =  df[football_columns].copy()

# check the new size of the dataset
print(df.shape)

df.head()

(380, 24)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,10,3,7,10,6,7,1,2,0,0
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,3,3,13,11,3,6,1,1,1,0
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,4,2,16,15,4,3,3,3,0,0
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,5,4,8,10,5,7,0,1,0,0
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,6,4,14,8,6,5,0,0,0,0

In [14]:
# check the data type

df.dtypes

Div           str
Date          str
Time          str
HomeTeam      str
AwayTeam      str
FTHG        int64
FTAG        int64
FTR           str
HTHG        int64
HTAG        int64
HTR           str
Referee       str
HS          int64
AS          int64
HST         int64
AST         int64
HF          int64
AF          int64
HC          int64
AC          int64
HY          int64
AY          int64
HR          int64
AR          int64
dtype: object

In [15]:
#Convet Date form str to int64

df["Date"] = pd.to_datetime(df["Date"], format= "%d/%m/%Y", errors= "coerce")

# check Date type
print(df["Date"].dtypes)

datetime64[us]

In [16]:
# check if all Date were converted
print("invalid dates: ", df["Date"].isnull().sum())

invalid dates:  0

In [17]:
# check uniques match result value

print("Full-time result: ", df["FTR"].unique())
print("Half-time result: ", df["HTR"].unique())

Full-time result:  <StringArray>
['H', 'D', 'A']
Length: 3, dtype: str
Half-time result:  <StringArray>
['H', 'D', 'A']
Length: 3, dtype: str

In [18]:
# check for negarive values in numeir football columns

numeric_colums = [
    "FTHG", "FTAG",
    "HTHG", "HTAG",
    "HS", "AS",
    "HST", "AST",
    "HF", "AF",
    "HC", "AC",
    "HY", "AY",
    "HR", "AR"
]


for c in numeric_colums:
    print(c, (df[c] < 0).sum())

FTHG 0
FTAG 0
HTHG 0
HTAG 0
HS 0
AS 0
HST 0
AST 0
HF 0
AF 0
HC 0
AC 0
HY 0
AY 0
HR 0
AR 0

In [19]:
# check if the shots on target HST are greter than the total shots HS

home_shot_errors = (df["HST"] > df["HS"]).sum()
away_shot_errors = (df["AST"] > df["AS"]).sum()

print("Home shot errors:", home_shot_errors)
print("Away shot errors:", away_shot_errors)

Home shot errors: 0
Away shot errors: 0

In [20]:
# chack the distrbution of match result

print(df["FTR"].value_counts())

print(df["FTR"].value_counts(normalize=True) * 100)

FTR
H    162
A    114
D    104
Name: count, dtype: int64
FTR
H    42.631579
A    30.000000
D    27.368421
Name: proportion, dtype: float64

In [21]:
# check the all the unique team names

team = sorted(set(df["HomeTeam"]) | set(df["AwayTeam"]))

print("Number of team: ", len(team))
print(team)

Number of team:  20
['Arsenal', 'Aston Villa', 'Bournemouth', 'Brentford', 'Brighton', 'Burnley', 'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Leeds', 'Liverpool', 'Man City', 'Man United', 'Newcastle', "Nott'm Forest", 'Sunderland', 'Tottenham', 'West Ham', 'Wolves']

In [22]:
#check if FTR matches the fulltime score

result_errors = df[

    ((df["FTHG"] > df["FTAG"]) & (df["FTR"] != "H")) |
    ((df["FTHG"] < df["FTAG"]) & (df["FTR"] != "A")) |
    ((df["FTHG"] == df["FTAG"]) & (df["FTR"] != "D"))
]

print("Number of result errors: ", len(result_errors))

result_errors

Number of result errors:  0

Empty DataFrame
Columns: [Div, Date, Time, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR]
Index: []

[0 rows x 24 columns]

In [23]:
#check if HTR matches the halftime score

half_time_errors = df[
    ((df["HTHG"] > df["HTAG"]) & (df["HTR"] != "H")) |
    ((df["HTHG"] < df["HTAG"]) & (df["HTR"] != "A")) |
    ((df["HTHG"] == df["HTAG"]) & (df["HTR"] != "D"))
]

print("Number of half-time result errors:", len(half_time_errors))

half_time_errors

Number of half-time result errors: 0

Empty DataFrame
Columns: [Div, Date, Time, HomeTeam, AwayTeam, FTHG, FTAG, FTR, HTHG, HTAG, HTR, Referee, HS, AS, HST, AST, HF, AF, HC, AC, HY, AY, HR, AR]
Index: []

[0 rows x 24 columns]

In [24]:
#final check for duplicates and missing values

print("Duplicate rows:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())
print("Final dataset shape:", df.shape)

Duplicate rows: 0
Missing values: 0
Final dataset shape: (380, 24)

In [25]:
df.to_csv("Data/E0_cleaned.cvs", index= False)